spring:
  application:
    name: gatewayServer
  config:
    import: optional:configserver:http://config-server:8082
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 1000
        max-attempts: 1000
        max-interval: 2000
        multiplier: 1.1